### PR TITLE
Define built-in copy of strndup as it is missing on Windows

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by derickr** [comment]
@mdashti I've slightly reworked this - can you check if this continues to work in your environment? And do I understand that this was found because you're integrating it into MongoDB?

**Comment by mdashti** [comment]
Thanks @derickr. Yes, I faced this issue while integrating the the latest tag of timelib into MongoDB. The change looks good to me and works on my environment.

**Comment by derickr** [comment]
Cheers, I've merged this. Would you want a new tag for this, or can that wait?

**Comment by mdashti** [comment]
Thanks @derickr. The integration with MongoDB is blocked and we're waiting on a new tag to avoid patching the library on our side. When do you think a new tag, e.g., `2021.04` will be available?

**Comment by derickr** [comment]
@mdashti I've pushed the `2021.04` tag.

**Pull request merged**
