### PR TITLE
Get rid of warnings about dropping const from timelib_tzd pointer

### PR DESCRIPTION
**Pull request by pprindeville**
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
Are we good to go with this PR?  It's pretty trivial.  Thanks.

**Comment by pprindeville** [comment]
@weltling @KalleZ @bukka Anyone able to nudge the owner on this one?

**Comment by weltling** [comment]
@pprindeville nope, Derick has the schedule where it's the best time to upgrade timelib in PHP.

Thanks.

**Comment by pprindeville** [comment]
@weltling nope, Derick has the schedule where it's the best time to upgrade timelib in PHP.

Understood.  I'd settle for knowing that the fix has been reviewed, accepted, and scheduled for merge...  Or if there's a `master` but PHP ships with tagged versions, then it could be merged now and cherry-picked into a tagged version later, whatever the strategy is.

**Comment by weltling** [comment]
@pprindeville it could be done this way for critical issues in PHP, that's true. But otherwise upgrades are delivered bulk with next timelib version. I'd suppose there were a better reasoning from Derick. From the PHP side - there was some case where the timelib upgrade had to be partially reverted due to unforeseen issues.

Thanks.

**Comment by nikic** [comment]
@derickr Ping, this PR looks like a no-brainer. Currently PHP calls this function with an explicit cast `timelib_timezone_identifiers_list((timelib_tzdb*) tzdb, &item_count)` to avoid the compiler warning.

**Comment by derickr** [comment]
I have merged this by hand, as it had to be re-targetted to the v2017 branch. Thanks!

**Comment by pprindeville** [comment]
Thanks!

**Pull request closed without merging**
