### PR TITLE
FIxed date diff calculation in respect of DST (see PHP bug #74524)

### PR DESCRIPTION
**Pull request by andrewnester**
Fix for https://bugs.php.net/bug.php?id=74524

### CODE REVIEW

**Comment by andrewnester** [comment]
@derickr any feedback on this?

**Comment by andrewnester** [comment]
@derickr could you please review it?

**Comment by derickr** [comment]
I'm not forgetting about this, just don't have a lot of time right now!

**Comment by raziel057** [comment]
Is it related to this issue https://bugs.php.net/bug.php?id=75167 ?

Please check the current issue: http://sandbox.onlinephpfunctions.com/code/c72ee88a5b71c71889139b5f7873a506914488e6

**Comment by derickr** [comment]
Sorry, this PR is too old, and I did forget about it :-(. I'm closing this, but this also seems similar to #24

**Pull request closed without merging**
