### PR TITLE
Improve timelib_unixtime2gmt() performance.

### PR DESCRIPTION
**Pull request by dstogov**
The impeoved algorithm is about ~4 times faster on 2021 dates.
The previous naive algorithm made 50 iterations (for each year since 1970).
The new algorithm makes one or two iterations for the same dates.

### CODE REVIEW

**Comment by dstogov** [comment]
@derickr please review, apply and update PHP master.

**Comment by derickr** [comment]
I've fixed this in a more elegant way. Thanks for pointing out the issue.

**Comment by dstogov** [comment]
Thanks.
It must be possible to optimize this a bit more by using 32-bit division.
May be I'll take a look when you land this to PHP.

I also wait for two other PRs.

**Comment by derickr** [comment]
On 18 March 2021 19:54:21 GMT, Dmitry Stogov ***@***.***> wrote:
>Thanks.
>It must be possible to optimize this a bit more by using 32-bit
>division.
>May be I'll take a look when you land this to PHP.
>
>I also wait for two other PRs. 

Two?

I have already merged https://github.com/derickr/timelib/pull/98 too as part of #14

**Comment by dstogov** [comment]
Oh, great. Than just one https://github.com/derickr/timelib/pull/99 Actually, I proposed just a simple workaround. It's better to avoid that linear search.

**Pull request closed without merging**
